// Generated by tools/build_racket_specs.py from the Shop sheet (tab RacketSpecs). Do not edit by hand.
window.RA_SPECS = {
"babolat-viper-2026-technical-soft": {
"shape": "Diamant",
"weight": "355–375",
"face": "Soft Carbon (Carbon Twill 3K)",
"core": "Black EVA",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Kopflastig"
},
"babolat-viper-2026-technical": {
"shape": "Diamant",
"weight": "360–380",
"face": "Carbon 3K",
"core": "EVA Hard",
"hard": "Hart",
"level": "Profi",
"balance": "Kopflastig"
},
"babolat-viper-2026-air": {
"shape": "Träne",
"weight": "345–365",
"face": "Carbon 16K",
"core": "X-EVA",
"hard": "Hart",
"level": "Fortgeschritten",
"balance": "Mittel"
},
"babolat-viper-2026-counter": {
"shape": "Rund",
"weight": "355–375",
"face": "Carbon 3K",
"core": "X-EVA",
"hard": "Hart",
"level": "Fortgeschritten",
"balance": "Kopflastig"
},
"babolat-viper-2026-lebron": {
"shape": "Diamant",
"weight": "360–380",
"face": "Carbon 3K",
"core": "EVA Hard",
"hard": "Hart",
"level": "Profi",
"balance": "Kopflastig"
},
"babolat-viper-soft-jl-3-1": {
"shape": "Diamant",
"weight": "355–375",
"face": "Soft Carbon (Carbon Twill)",
"core": "Black EVA",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Kopflastig"
},
"babolat-veron-2026-technical": {
"shape": "Diamant",
"weight": "350–370",
"face": "Carbon Flex (Carbon/Fiberglas)",
"core": "Black EVA",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Kopflastig"
},
"babolat-veron-2026-air": {
"shape": "Träne",
"weight": "345–365",
"face": "Carbon Flex (Carbon/Fiberglas)",
"core": "Black EVA",
"hard": "Mittel",
"level": "Amateur",
"balance": "Mittel"
},
"wilson-endure-pro": {
"shape": "Rund",
"weight": "355–375",
"face": "Carbon 3K",
"core": "Control Foam+ (Dual-Density)",
"hard": "Hart",
"level": "Profi",
"balance": "Mittel"
},
"wilson-endure": {
"shape": "Rund",
"weight": "355–375",
"face": "Carbon UD",
"core": "Control Foam+ (Dual-Density)",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Grifflastig"
},
"wilson-endure-ls": {
"shape": "Rund",
"weight": "345–365",
"face": "Carbon Flex",
"core": "Control Foam+ (Dual-Density)",
"hard": "Mittel",
"level": "Amateur",
"balance": "Grifflastig"
},
"wilson-blade-ls-green": {
"shape": "Träne",
"weight": "355",
"face": "Fiberglas",
"core": "EVA Soft",
"hard": "Weich",
"level": "Fortgeschritten",
"balance": "Mittel"
},
"wilson-blade-ls-rosa": {
"shape": "Träne",
"weight": "355",
"face": "Fiberglas",
"core": "EVA Soft",
"hard": "Weich",
"level": "Fortgeschritten",
"balance": "Mittel"
},
"wilson-bela-pro": {
"shape": "Diamant",
"weight": "370",
"face": "Carbon (Primero Carbon)",
"core": "EVA Hard",
"hard": "Hart",
"level": "Profi",
"balance": "Mittel"
},
"wilson-defy-white": {
"shape": "Diamant",
"weight": "360–370",
"face": "Carbon 3K",
"core": "Power Foam",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Mittel"
},
"wilson-defy-ls-white": {
"shape": "Diamant",
"weight": "355–365",
"face": "Comfort Flex (Carbon/Fiberglas)",
"core": "Power Foam",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Mittel"
},
"wilson-defy-pro": {
"shape": "Diamant",
"weight": "360–380",
"face": "Carbon 15K",
"core": "Power Foam",
"hard": "Hart",
"level": "Profi",
"balance": "Mittel"
},
"wilson-defy": {
"shape": "Diamant",
"weight": "355–375",
"face": "Carbon 3K",
"core": "Power Foam",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Mittel"
},
"wilson-defy-ls": {
"shape": "Diamant",
"weight": "345–365",
"face": "Comfort Flex (Carbon/Fiberglas)",
"core": "Power Foam",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Mittel"
},
"wilson-bela-v3": {
"shape": "Träne",
"weight": "355–375",
"face": "Carbon 3K",
"core": "Power Foam",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Mittel"
},
"wilson-bela-v3-pro": {
"shape": "Träne",
"weight": "360–380",
"face": "Carbon 24K",
"core": "Power Foam",
"hard": "Hart",
"level": "Profi",
"balance": "Mittel"
},
"wilson-bela-v3-ls": {
"shape": "Träne",
"weight": "345–365",
"face": "Comfort Flex (Carbon/Fiberglas)",
"core": "Power Foam",
"hard": "Mittel",
"level": "Fortgeschritten",
"balance": "Mittel"
},
"siux-diablo-pro-royal-blue-2026": {
"shape": "Träne",
"weight": "365–375",
"face": "Carbon 18K (TeXtreme)",
"core": "EVA (mittlere Dichte)",
"hard": "Mittel",
"level": "Profi",
"balance": "Mittel"
},
"siux-pegasus-pro-storm-grey-2026": {
"shape": "Träne",
"weight": "355–375",
"face": "Carbon 12K",
"core": "EVA Hard (EVA Pro)",
"hard": "Hart",
"level": "Profi",
"balance": "Mittel"
},
"siux-fenix-pro-2026-black-purple": {
"shape": "Diamant",
"weight": "355–375",
"face": "Carbon 12K",
"core": "EVA Hard (High Density)",
"hard": "Hart",
"level": "Profi",
"balance": "Kopflastig"
},
"siux-trilogy-pro-2026-ash-green": {
"shape": "Rund",
"weight": "355–375",
"face": "Carbon 24K",
"core": "EVA (mittel-hart)",
"hard": "Hart",
"level": "Profi",
"balance": "Grifflastig"
},
"siux-electra4-pro-grey-2026": {
"shape": "Träne",
"weight": "355–375",
"face": "Carbon 12K",
"core": "EVA",
"hard": "Hart",
"level": "Profi",
"balance": "Mittel"
}
};
