"""Racket specs (shape, weight, face, core, hardness, level, balance) -> racket-specs.js.
Source of truth: Shop sheet, tab "RacketSpecs" (export it to tools/racket_specs.json as [[header...],[row...]])."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rows = json.load(open(os.path.join(ROOT, 'tools', 'racket_specs.json')))
head, data = rows[0], rows[1:]
K = {'Form': 'shape', 'Gewicht (g)': 'weight', 'Fläche': 'face', 'Kern': 'core', 'Härte': 'hard', 'Niveau': 'level', 'Balance': 'balance'}
out = {}
for r in data:
    r = r + [''] * (len(head) - len(r))
    d = {K[h]: str(v).strip() for h, v in zip(head, r) if h in K}
    out[r[0]] = d
js = '// Generated by tools/build_racket_specs.py from the Shop sheet (tab RacketSpecs). Do not edit by hand.\nwindow.RA_SPECS = ' + json.dumps(out, ensure_ascii=False, indent=0) + ';\n'
open(os.path.join(ROOT, 'racket-specs.js'), 'w').write(js)
print(len(out), 'rackets')
